@startuml
skinparam classAttributeIconSize 0

' Clase base del sistema
class Exception {
  + Exception(message: String)
}

' Excepción Personalizada 1
class MiExcepcion {
  + MiExcepcion(mensaje: String)
}

' Excepción Personalizada 2
class ExcepcionPersonalizada2 {
  + ExcepcionPersonalizada2(mensaje: String)
}

' Clase principal de uso
class EjemploExcepciones {
  + main(args: String[]) : void
  + validarParametro(valor: int) : void
}

' Relaciones de Herencia
Exception <|-- MiExcepcion
Exception <|-- ExcepcionPersonalizada2

' Relación de Dependencia (uso/lanzamiento)
EjemploExcepciones ..> MiExcepcion : <<throws>>
EjemploExcepciones ..> ExcepcionPersonalizada2 : <<throws>>

@enduml